// src/validators/verifiedNumberValidator.js
const { z } = require('zod');

/**
 * Validation schemas for the VerifiedNumber admin API.
 *
 * `VerifiedNumber` is the identity table for the whole stack, so these schemas are
 * deliberately strict: only the columns an admin is allowed to set are accepted, and
 * `.strict()` makes a stray `id` / `created_at` / `twenty_user_id` a 400 rather than a
 * silently ignored key. Normalization (case, trimming, phone format) is the service's
 * job — these schemas only decide shape.
 */

/** Blank strings from an HTML form mean "unset", not "set to empty". */
const optionalText = z
    .string()
    .trim()
    .transform((v) => (v === '' ? null : v))
    .nullable()
    .optional();

const emailField = z
    .string()
    .trim()
    .email('email must be a valid email address')
    .transform((v) => (v === '' ? null : v))
    .nullable()
    .optional();

/** 10-15 digits once punctuation is stripped — matches commonSchemas.phone. */
const phoneField = z
    .string()
    .trim()
    .refine((v) => v.replace(/\D/g, '').length >= 10 && v.replace(/\D/g, '').length <= 15, {
        message: 'phone_number must contain between 10 and 15 digits',
    });

const capabilityFields = {
    adminAccess: z.boolean().optional(),
    callDashboardAccess: z.boolean().optional(),
    dashboardAccess: z.boolean().optional(),
    reviewerAccess: z.boolean().optional(),
};

class VerifiedNumberValidator {
    /** Query params for the admin roster list. */
    static listQuerySchema = z.object({
        search: z.string().trim().max(200).optional(),
        // Checkbox-style query params arrive as strings.
        includeInactive: z
            .union([z.boolean(), z.enum(['true', 'false'])])
            .transform((v) => v === true || v === 'true')
            .optional(),
    });

    /** Integer row id route param. */
    static idSchema = z.object({
        id: z.coerce.number().int().positive('id must be a positive integer'),
    });

    /**
     * Create body. `name` plus at least one contact identity is required: a row with
     * neither an email nor a phone number can never be matched by any consumer
     * (access.js matches on email, the WhatsApp bot on phone), so it would be inert.
     * `empID` is generated by the service and is not accepted here.
     */
    static createSchema = z
        .object({
            name: z.string().trim().min(1, 'name is required'),
            email: emailField,
            phone_number: phoneField.optional(),
            role: optionalText,
            is_active: z.boolean().optional(),
            ...capabilityFields,
        })
        .strict()
        .refine((d) => d.email != null || d.phone_number != null, {
            message: 'at least one of email or phone_number is required',
            path: ['email'],
        });

    /**
     * Update body — a strict partial. `confirmIdentityChange` is not a column: it is
     * the caller acknowledging that editing `phone_number` / `empID` will cascade to
     * WhatsApp bot state and Scout logins.
     */
    static updateSchema = z
        .object({
            name: z.string().trim().min(1, 'name cannot be empty').optional(),
            email: emailField,
            phone_number: phoneField.optional(),
            empID: z.string().trim().min(1).optional(),
            role: optionalText,
            is_active: z.boolean().optional(),
            confirmIdentityChange: z.boolean().optional(),
            ...capabilityFields,
        })
        .strict()
        .refine((d) => Object.keys(d).some((k) => k !== 'confirmIdentityChange'), {
            message: 'no fields to update',
        });
}

module.exports = VerifiedNumberValidator;
